@startuml
Bed }|.u.|| Room
Room }|.l.|| Station
Bed ||..o{ Bed_Patient
Bed_Patient }|..|| Patient
Patient ||..|{ Patient_MedicalStaff
MedicalStaff ||..|{ Patient_MedicalStaff
MedicalStaff <|.. Doctor
MedicalStaff <|.. Nurse
Person <|.. MedicalStaff
Person <|.. Patient

Patient ||..|{ Patient_Condition
Condition ||.u.|{ Patient_Condition

circle "Komposite Key (Zeit, Bed, Patient)"


@enduml

