### Patient Requests
POST http://localhost:8080/patient/addPatient
Content-Type: application/json

{
  "ssn": "8d879",
  "firstName": "patient1",
  "lastName": "plastname",
  "conditions": []
}

###
GET http://localhost:8080/patient/getAllPatients

### Room Requests
GET http://localhost:8080/room/getAll

###

GET http://localhost:8080/room/findById/1
