### Patient Requests
POST http://localhost:8080/api/patient/addPatient
Content-Type: application/json

{
  "ssn": "8d879",
  "firstName": "patient1",
  "lastName": "plastname",
  "conditions": []
}

### Condition Requests
POST http://localhost:8080/api/condition/addCondition
Content-Type: application/json

{
  "name": "schnupfen",
  "description": "rinnende nase"
}
###
GET http://localhost:8080/api/condition/getAllConditions

###
GET http://localhost:8080/api/patient/getAllPatients

### Room Requests
GET http://localhost:8080/api/room/getAllRooms

###

GET http://localhost:8080/api/room/findRoomById/1

###

POST http://localhost:8080/api/patient/addConditionForPatient?condition=1&patient=1

###

GET http://localhost:8080/api/bed/getAllBeds

###

GET http://localhost:8080/api/station/getAllStations

###

GET http://localhost:8080/api/roomType/getAllRoomTypes

###

GET http://localhost:8080/api/patient/getBedPatientById/1/1
